AWSTemplateFormatVersion: 2010-09-09

Parameters:

  StackPrefix:
    Type: String

  ALBDomain:
    Type: String

  AppDomain:
    Type: String

  PublicTLDHostedZoneId:
    Type: String

Resources:

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref AppDomain
      ValidationMethod: DNS
      DomainValidationOptions: 
        - HostedZoneId: !Ref PublicTLDHostedZoneId
          DomainName: !Ref AppDomain

  CloudfrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub CDN for ${StackPrefix}
        WebACLId:
          Fn::ImportValue:
            !Sub ${StackPrefix}-waf-acl
        Origins:
          - DomainName: !Ref ALBDomain
            Id: ALBOrigin
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: ''
        Aliases:
          - !Ref AppDomain
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          Compress: true
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: ALBOrigin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
        Restrictions:
          GeoRestriction:
            RestrictionType: blacklist
            Locations:
              - KP
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  AppDNSAlias:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PublicTLDHostedZoneId
      Name: !Ref AppDomain
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudfrontDistro.DomainName
