AWSTemplateFormatVersion: 2010-09-09

Parameters:

  StackPrefix:
    Type: String

  PublicTLD:
    Type: String

  PublicTLDHostedZoneId:
    Type: String

  ALBSubdomain:
    Type: String

  SampleAppSubdomain:
    Type: String

  PrivateTLD:
    Type: String

Resources:

  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref PrivateTLD
      VPCs:
        - VPCRegion: !Ref AWS::Region
          VPCId:
            Fn::ImportValue:
              !Sub ${StackPrefix}-vpc

Outputs:
  PublicTLD:
    Value: !Ref PublicTLD
    Export:
      Name: !Sub ${StackPrefix}-dns-publictld
  PrivateTLD:
    Value: !Ref PrivateTLD
    Export:
      Name: !Sub ${StackPrefix}-dns-privatetld
  PublicTLDHostedZone:
    Value: !Ref PublicTLDHostedZoneId
    Export:
      Name: !Sub ${StackPrefix}-dns-publichzi
  PrivateTLDHostedZone:
    Value: !Ref PrivateHostedZone
    Export:
      Name: !Sub ${StackPrefix}-dns-privatehzi
  AppPublicDNS:
    Value: !Sub ${SampleAppSubdomain}.${PublicTLD}
    Export:
      Name: !Sub ${StackPrefix}-dns-app-name
  ALBDomain:
    Value: !Sub ${ALBSubdomain}.${PublicTLD}
    Export:
      Name: !Sub ${StackPrefix}-dns-alb-name
  DBPrivateDNS:
    Value: !Sub db.${PrivateTLD}
    Export:
      Name: !Sub ${StackPrefix}-dns-db-name
  DBReadPrivateDNS:
    Value: !Sub db-read.${PrivateTLD}
    Export:
      Name: !Sub ${StackPrefix}-dns-db-readname
