AWSTemplateFormatVersion: 2010-09-09

Parameters:

  StackPrefix:
    Type: String

  PublicTLD:
    Type: String

Resources:

  LimitRequestSize:
    Type: AWS::WAFRegional::SizeConstraintSet
    Properties:
      Name: !Sub ${StackPrefix}LimitRequestSize
      SizeConstraints:
        - ComparisonOperator: GT
          FieldToMatch:
            Type: BODY
          Size: 512
          TextTransformation: NONE
        - ComparisonOperator: GT
          FieldToMatch:
            Type: QUERY_STRING
          Size: 16
          TextTransformation: NONE

  DetectSQLi:
    Type: AWS::WAFRegional::SqlInjectionMatchSet
    Properties:
      Name: !Sub ${StackPrefix}DetectSQLi
      SqlInjectionMatchTuples:
        - FieldToMatch:
            Type: URI
          TextTransformation: NONE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: NONE
        - FieldToMatch:
            Type: URI
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: URI
          TextTransformation: COMPRESS_WHITE_SPACE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: COMPRESS_WHITE_SPACE
        - FieldToMatch:
            Type: URI
          TextTransformation: CMD_LINE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: CMD_LINE

  DetectXSS:
    Type: AWS::WAFRegional::XssMatchSet
    Properties:
      Name: !Sub ${StackPrefix}DetectXSS
      XssMatchTuples:
        - FieldToMatch:
            Type: URI
          TextTransformation: NONE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: NONE
        - FieldToMatch:
            Type: URI
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: URI
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: URL_DECODE

  RefererMatch:
    Type: AWS::WAFRegional::ByteMatchSet
    Properties:
      Name: !Sub ${StackPrefix}RefererHeader
      ByteMatchTuples:
      ByteMatchTuples:
        - FieldToMatch:
            Type: HEADER
            Data: Referer
          TargetString: https://
          TextTransformation: LOWERCASE
          PositionalConstraint: STARTS_WITH
        - FieldToMatch:
            Type: HEADER
            Data: Referer
          TargetString: !Sub .${PublicTLD}/
          TextTransformation: LOWERCASE
          PositionalConstraint: ENDS_WITH

  HostMatch:
    Type: AWS::WAFRegional::ByteMatchSet
    Properties:
      Name: !Sub ${StackPrefix}HostHeader
      ByteMatchTuples:
        - FieldToMatch:
            Type: HEADER
            Data: Host
          TargetString: !Sub .${PublicTLD}
          TextTransformation: LOWERCASE
          PositionalConstraint: ENDS_WITH

  RefererExistsMatch:
    Type: AWS::WAFRegional::SizeConstraintSet
    Properties:
      Name: !Sub ${StackPrefix}RefererExists
      SizeConstraints:
        - ComparisonOperator: GE
          FieldToMatch:
            Type: HEADER
            Data: Referer
          Size: 1
          TextTransformation: NONE

  SecurityRule:
    Type: AWS::WAFRegional::Rule
    Properties:
      Name: !Sub ${StackPrefix}SecurityRule
      MetricName: SecurityRule
      Predicates:
        - DataId: !Ref LimitRequestSize
          Negated: false
          Type: SizeConstraint
        - DataId: !Ref DetectSQLi
          Negated: false
          Type: SqlInjectionMatch
        - DataId: !Ref DetectXSS
          Negated: false
          Type: XssMatch

  ValidRefererRule:
    Type: AWS::WAFRegional::Rule
    Properties:
      Name: !Sub ${StackPrefix}RefererRule
      MetricName: RefererRule
      Predicates:
        - DataId: !Ref RefererMatch
          Negated: false
          Type: ByteMatch

  InvalidHostRule:
    Type: AWS::WAFRegional::Rule
    Properties:
      Name: !Sub ${StackPrefix}InvalidHostRule
      MetricName: InvalidHostRule
      Predicates:
        - DataId: !Ref HostMatch
          Negated: true
          Type: ByteMatch

  EmptyRefererRule:
    Type: AWS::WAFRegional::Rule
    Properties:
      Name: !Sub ${StackPrefix}EmptyRefererRule
      MetricName: EmptyRefererRule
      Predicates:
        - DataId: !Ref RefererExistsMatch
          Negated: true
          Type: SizeConstraint

  # RateLimiterRule:
  #   Type: AWS::WAFRegional::RateBasedRule
  #   Properties:
  #     Name: RateLimiterRule
  #     MetricName: RateLimiterRule
  #     RateKey: IP
  #     RateLimit: 2000

  WAFACL:
    Type: AWS::WAFRegional::WebACL
    Properties:
      Name: !Sub ${StackPrefix} ACL
      DefaultAction:
        Type: BLOCK
      MetricName: !Sub ${StackPrefix}ACL
      Rules:
        - Action:
            Type: BLOCK
          Priority: 1
          RuleId: !Ref InvalidHostRule
        - Action:
            Type: BLOCK
          Priority: 2
          RuleId: !Ref SecurityRule
        - Action:
            Type: ALLOW
          Priority: 3
          RuleId: !Ref ValidRefererRule
        - Action:
            Type: ALLOW
          Priority: 4
          RuleId: !Ref EmptyRefererRule


Outputs:
  WAFACL:
    Value: !Ref WAFACL
    Export:
      Name: !Sub ${StackPrefix}-waf-regional-acl
